#!/bin/bash

#Script Generates new /etc/interfaces file based on user input
#Restarts wifi to connect to actual network

sudo cp /etc/network/interfaces /etc/network/interfaces_bckup
sudo rm /etc/network/interfaces

#get SSID from User
echo "Enter SSID: "
#Read SSID from Input
read SSID
#Get Password from user
echo "Enter password: "
#Read password from input
read PWD


function writeinterfaces
{

cat << _EOF_

#/etc/network/interfaces generated on $(date)

#### ORIGINAL INTERFACES FROM RASPBERRY PI ####
#auto lo
#iface lo inet loopback
#iface eth0 inet dhcp

#allow-hotplug wlan0
#iface wlan0 inet manual
#wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
#iface default inet dhcp
#### End Original Interfaces ####

#### BEGIN Generated Interfaces
auto wlan0
iface wlan0 inet dhcp
wpa-ssid "$SSID"
wpa-psk "$PWD"
#### END Generated Interfaces

#### Ad-Hoc Network Interfaces Configuration
#auto lo
#iface lo inet loopback
#iface eth0 inet dhcp

#auto wlan0
#iface wlan0 inet static
#	address 192.168.1.1
#	netmask 255.255.255.0
#	wireless-channel 1
#	wireless-essid RasPi_AdHoc
#	wireless-mode ad-hoc

_EOF_
}

writeinterfaces > /etc/network/interfaces

#Shut down, then  restart interface for WiFi wlan0
#sudo ifdown --force wlanb0
#sudo ifup --force wlan0

#sudo /etc/init.d/networking restart


#Send user warning that system will reboot
echo
echo "		--		"
echo "  Interfaces Generated"
echo " Raspberry Pi will try to connect"
echo "		--		"
echo "*******************************"
echo "WARNING! SYSTEM WILL NOW REBOOT"
echo "*******************************"

sudo reboot
